<a href="https://colab.research.google.com/github/dondiana/pp2/blob/main/Data_preparation_p1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1 Import the numpy package under the name np
import numpy as np
#2 Print the numpy version and the configuration
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

In [ ]:
#3 Create a null vector of size 10
import numpy as np
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#4 How to find the memory size of any array
import numpy as np
array = np.array([1,2,3])
memory_size = array.nbytes
print(memory_size)

24


In [ ]:
#5 How to get the documentation of the numpy add function from the command line?
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [ ]:
#6 Create a null vector of size 10 but the fifth value which is 1
import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#7  Create a vector with values ranging from 10 to 49
import numpy as np
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#8 Reverse a vector (first element becomes last)
import numpy as np
vector = np.arange(1,11)
reversed_vector = vector[::-1]
print(reversed_vector)

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
#9 Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
matrix = np.arange(9).reshape(3, 3)
print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#10 Find indices of non-zero elements from [1,2,0,0,4,0]
import numpy as np
array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(array)
print(non_zero_indices)

(array([0, 1, 4]),)


In [ ]:
#11 Create a 3x3 identity matrix
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#12 Create a 3x3x3 array with random values
import numpy as np
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.30957525 0.01927775 0.55615336]
  [0.05724445 0.17432607 0.66801193]
  [0.25363151 0.84228096 0.82568055]]

 [[0.20873957 0.73078149 0.046062  ]
  [0.67288078 0.37093816 0.24556326]
  [0.92577205 0.19583882 0.41836314]]

 [[0.08848092 0.67365041 0.054168  ]
  [0.04762419 0.81965427 0.86934801]
  [0.50239217 0.83285076 0.3651924 ]]]


In [ ]:
#13 Create a 10x10 array with random values and find the minimum and maximum values
import numpy as np
random_array = np.random.rand(10,10)
min_value = np.min(random_array)
max_value = np.max(random_array)
print("Random Array:\n", random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Random Array:
 [[0.66041627 0.61914069 0.78579484 0.95969833 0.09311513 0.8768487
  0.78433314 0.52004776 0.29963204 0.45388064]
 [0.31777369 0.94011546 0.95393578 0.61334442 0.04581765 0.92927811
  0.85448432 0.68497804 0.66245197 0.20376779]
 [0.04526324 0.37190124 0.57735324 0.05173411 0.53935503 0.39007712
  0.38969688 0.2905175  0.5199429  0.4352086 ]
 [0.6248025  0.39967266 0.25872253 0.35828537 0.79239146 0.95769331
  0.18602362 0.24370354 0.72670276 0.07022315]
 [0.14294261 0.39588557 0.5607221  0.09736959 0.66083379 0.80951185
  0.77179597 0.59528625 0.69436891 0.63260151]
 [0.42433257 0.51663471 0.46692228 0.3919928  0.94169788 0.26657094
  0.42787152 0.65012911 0.29006907 0.09045838]
 [0.65175554 0.0493438  0.31434846 0.12068599 0.87889048 0.20958246
  0.4838471  0.6406315  0.39109894 0.27992424]
 [0.49065877 0.59610652 0.98558979 0.58295377 0.34967327 0.48302149
  0.64329672 0.16031985 0.7245935  0.13232355]
 [0.09376091 0.15709682 0.75754333 0.22243337 0.16346572 0.4996150

In [ ]:
#14 Create a random vector of size 30 and find the mean value
import numpy as np
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print("Random vector:/n", random_vector)
print("Mean value:", mean_value)

Random vector:/n [0.86907706 0.65309812 0.89634778 0.28923081 0.37056335 0.52634112
 0.70872401 0.73565628 0.26499587 0.56444104 0.78097303 0.62159668
 0.73367796 0.98342295 0.64248972 0.71460335 0.97558228 0.97901315
 0.72209618 0.25259674 0.63349476 0.0912722  0.00125326 0.79666899
 0.38839113 0.08539729 0.75056703 0.20074484 0.91766626 0.77606928]
Mean value: 0.5975350835045644


In [ ]:
#15 Create a 2d array with 1 on the border and 0 inside
import numpy as np
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#16 How to add a border (filled with 0's) around an existing array?
import numpy as np
array = np.ones((3, 3))
padded_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
# pad_width=1 specifies that you want to add a border of width 1 on all sides.
# mode='constant' means you are filling the border with a constant value.
# constant_values=0 specifies that the constant value for padding should be 0.
print(padded_array)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#17 What is the result of the following expression?\
import numpy as np
a = 0 * np.nan
print("0 * np.nan:", a)
b = np.nan == np.nan
print("np.nan == np.nan:", b)
c = np.inf > np.nan
print("np.inf > np.nan:", c)
d = np.nan - np.nan
print("np.nan - np.nan:", d)
e = np.nan in set([np.nan])
print("np.nan in set([np.nan]):", e)
f = 0.3 == 3 * 0.1
print("0.3 == 3 * 0.1:", f)

0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
np.nan in set([np.nan]): True
0.3 == 3 * 0.1: False


In [ ]:
#18 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
import numpy as np
matrix = np.diag([1, 2, 3, 4], k=-1)
# k=-1 means below the main diagonal
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#19 Create a 8x8 matrix and fill it with a checkerboard pattern
import numpy as np
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # Fill rows starting from 1, every 2nd row, starting at 0th column
checkerboard[::2, 1::2] = 1  # Fill rows starting from 0, every 2nd row, starting at 1st column
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#20 Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
import numpy as np
shape = (6, 7, 8)
# Find the index of the 100th element (indexing starts at 0, so 100th element has index 99)
index = np.unravel_index(99, shape)
print(index)

(1, 5, 3)


In [ ]:
#21 Create a checkerboard 8x8 matrix using the tile function
import numpy as np
checkerboard_pattern = np.array([[0, 1],
                                 [1, 0]])
# Use np.tile() to repeat this pattern in an 8x8 grid
checkerboard = np.tile(checkerboard_pattern, (4, 4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#22 Normalize a 5x5 random matrix
import numpy as np
random_matrix = np.random.rand(5, 5)
# Normalize the matrix: (matrix - min) / (max - min)
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))
print("Original Matrix:\n", random_matrix)
print("\nNormalized Matrix:\n", normalized_matrix)


Original Matrix:
 [[0.78901502 0.26575643 0.28111459 0.33701384 0.03593306]
 [0.44844593 0.80671223 0.70074689 0.04501844 0.57856493]
 [0.19112338 0.16287917 0.048155   0.54848106 0.52599028]
 [0.2740047  0.7710462  0.96294316 0.24035619 0.1618955 ]
 [0.27585311 0.72838023 0.81770288 0.75330737 0.35632851]]

Normalized Matrix:
 [[0.8123773  0.24791895 0.26448636 0.32478695 0.        ]
 [0.44499285 0.83146794 0.71715921 0.00980074 0.58535703]
 [0.16740952 0.13694145 0.01318426 0.55290444 0.52864281]
 [0.25681667 0.79299367 1.         0.22051878 0.13588034]
 [0.25881061 0.74696832 0.84332395 0.77385814 0.34562239]]


In [ ]:
#23 Create a custom dtype that describes a color as four unsigned bytes (RGBA)
import numpy as np
rgba_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])
# Create an example array with this dtype
colors = np.array([(255, 0, 0, 255),   # Red
                   (0, 255, 0, 255),   # Green
                   (0, 0, 255, 255),   # Blue
                   (255, 255, 0, 255)], # Yellow
                 dtype=rgba_dtype)
print(colors)

[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255,   0, 255)]


In [ ]:
#24 Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
import numpy as np
matrix_5x3 = np.random.rand(5, 3)
matrix_3x2 = np.random.rand(3, 2)
result = np.dot(matrix_5x3, matrix_3x2)
print("5x3 Matrix:\n", matrix_5x3)
print("\n3x2 Matrix:\n", matrix_3x2)
print("\nResulting 5x2 Matrix:\n", result)

5x3 Matrix:
 [[0.69826813 0.77182637 0.87818456]
 [0.78081107 0.45212693 0.39365239]
 [0.83899935 0.30819239 0.34149567]
 [0.1513996  0.96103834 0.28714021]
 [0.5338892  0.2616763  0.93298404]]

3x2 Matrix:
 [[0.45692586 0.66111327]
 [0.85268627 0.74233222]
 [0.4272133  0.45655503]]

Resulting 5x2 Matrix:
 [[1.35235463 1.43552549]
 [0.91046873 1.03155692]
 [0.7920434  0.9393663 ]
 [1.01131271 0.94459732]
 [0.86565876 0.97317054]]


In [ ]:
#25 Given a 1D array, negate all elements which are between 3 and 8, in place.
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Negate all elements between 3 and 8 (inclusive)
array[(array > 3) & (array <= 8)] *= -1
print(array)

[ 1  2  3 -4 -5 -6 -7 -8  9 10]
